name: agent-ci

on:
  pull_request:
    branches: ["main"]
    paths:
      - "generated/**"
      - ".github/workflows/agent-ci.yml"
  workflow_dispatch:
    inputs:
      task:
        description: "Optional: comma-separated <taskId>/<slug> values (e.g., abc,def)"
        required: false
        type: string
      max-tests:
        description: "Number of tests per task (0 or empty = all)"
        required: false
        type: string
        default: "0"

permissions:
  contents: read
  pull-requests: read
  actions: read

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      tasks: ${{ steps.discover.outputs.tasks }}
    steps:
      - name: Discover changed tasks
        id: discover
        uses: actions/github-script@v7
        with:
          script: |
            const tasks = new Set();

            if (context.eventName === 'workflow_dispatch') {
              const raw = core.getInput('task') || '';
              for (const t of raw.split(',').map(s => s.trim()).filter(Boolean)) {
                tasks.add(t);
              }
            } else {
              const { owner, repo } = context.repo;
              const prNumber = context.payload.pull_request.number;
              const perPage = 100;
              let page = 1;
              while (true) {
                const { data } = await github.rest.pulls.listFiles({
                  owner, repo, pull_number: prNumber, per_page: perPage, page
                });
                for (const f of data) {
                  // Match either generated/<taskId>/...  OR  generated/stories/<slug>/...
                  let m = /^generated\/([^/]+)\//.exec(f.filename);
                  if (m) { tasks.add(m[1]); continue; }
                  m = /^generated\/stories\/([^/]+)\//.exec(f.filename);
                  if (m) { tasks.add(m[1]); continue; }
                }
                if (data.length < perPage) break;
                page++;
              }
            }

            let arr = Array.from(tasks);
            if (arr.length === 0) {
              // Ensure downstream job runs and logs why it’s a no-op
              arr = ["__none__"];
            }
            core.info(`Discovered tasks: ${JSON.stringify(arr)}`);
            core.setOutput('tasks', JSON.stringify(arr));

  test:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task: ${{ fromJson(needs.discover.outputs.tasks) }}
    env:
      # Prefer manual input; else repo variable MAX_TESTS; else "0" (meaning "all")
      MAX_TESTS: ${{ (github.event_name == 'workflow_dispatch' && inputs.max-tests) || vars.MAX_TESTS || '0' }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Echo selected task
        run: echo "Matrix task='${{ matrix.task }}'"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install base deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
          pip install pytest

      - name: Early exit if sentinel
        if: ${{ matrix.task == '__none__' }}
        run: |
          echo "No changed tasks detected by discover; nothing to test."
          exit 0

      - name: Per-task optional deps
        run: |
          set -euo pipefail
          # Support both layouts:
          #   generated/<taskId>/...
          #   generated/stories/<slug>/...
          if [ -d "generated/${{ matrix.task }}" ]; then
            TASK="generated/${{ matrix.task }}"
          elif [ -d "generated/stories/${{ matrix.task }}" ]; then
            TASK="generated/stories/${{ matrix.task }}"
          else
            echo "Task path not found for '${{ matrix.task }}'"; exit 0
          fi

          if [ -f "$TASK/requirements.txt" ]; then pip install -r "$TASK/requirements.txt"; fi
          if [ -f "$TASK/tests/requirements.txt" ]; then pip install -r "$TASK/tests/requirements.txt"; fi

      - name: Run up to ${{ env.MAX_TESTS }} test(s) for ${{ matrix.task }}
        run: |
          set -euo pipefail
          if [ -d "generated/${{ matrix.task }}" ]; then
            TASK="generated/${{ matrix.task }}"
          elif [ -d "generated/stories/${{ matrix.task }}" ]; then
            TASK="generated/stories/${{ matrix.task }}"
          else
            echo "Task path not found for '${{ matrix.task }}'"; exit 0
          fi

          if [ ! -d "$TASK/src" ] || [ ! -d "$TASK/tests" ]; then
            echo "Skipping $TASK (missing src/ or tests/)."
            exit 0
          fi

          export PYTHONPATH="$TASK/src${PYTHONPATH:+:$PYTHONPATH}"

          N="${MAX_TESTS:-0}"
          if [[ -z "$N" || "$N" == "0" || "$N" == "all" || ! "$N" =~ ^[0-9]+$ || "$N" -le 0 ]]; then
            echo "Running ALL tests for $TASK"
            pytest -q --junitxml "$TASK/ci-results.xml" "$TASK/tests"
            exit 0
          fi

          mapfile -t NODEIDS < <(pytest --collect-only -q "$TASK/tests" 2>/dev/null | sed '/::/!d' | head -n "$N")
          if [ "${#NODEIDS[@]}" -eq 0 ]; then
            echo "No tests collected for $TASK"
            exit 0
          fi

          echo "Running ${#NODEIDS[@]} test(s):"
          printf '  %s\n' "${NODEIDS[@]}"

          pytest -q --junitxml "$TASK/ci-results.xml" "${NODEIDS[@]}"

      - name: Upload JUnit report for ${{ matrix.task }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{ matrix.task }}
          path: |
            generated/${{ matrix.task }}/ci-results.xml
            generated/stories/${{ matrix.task }}/ci-results.xml
          if-no-files-found: ignore
