name: agent-ci
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/*.py"
      - "tests/**"
  workflow_dispatch:
    branches: [ "main" ]
    paths:
      - "generated/*/src/*.py"
      - "generate/*/tests/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
          pip install pytest
      - name: Run tests
        run: pytest -q
