name: agent-ci

on:
  pull_request:
    branches: ["main"]
    paths:
      - "generated/**" # trigger when generated content changes
      - ".github/workflows/agent-ci.yml"
  workflow_dispatch: {} # manual run; no paths/branches filters supported

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # helpful if you later diff changed tasks
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
          pip install pytest
      - name: Run at most 2 tests for task ${{ matrix.task }}
        run: |
          set -euo pipefail
          TASK="generated/${{ matrix.task }}"
          if [ ! -d "$TASK/tests" ]; then
            echo "No tests found in $TASK"
            exit 0
          fi

          export PYTHONPATH="$TASK/src${PYTHONPATH:+:$PYTHONPATH}"

          # Collect pytest node IDs and keep only the first 2
          mapfile -t NODEIDS < <(pytest --collect-only -q "$TASK/tests" 2>/dev/null | sed '/::/!d' | head -n 2)

          if [ "${#NODEIDS[@]}" -eq 0 ]; then
            echo "No tests collected."
            exit 0
          fi

          echo "Running ${#NODEIDS[@]} test(s):"
          printf '  %s\n' "${NODEIDS[@]}"

          pytest -q "${NODEIDS[@]}"
